export const HTTP_STATUS = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  SERVICE_UNAVAILABLE: 503,
} as const

export type AuthStatus =
  typeof HTTP_STATUS.UNAUTHORIZED | typeof HTTP_STATUS.FORBIDDEN
